// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbTCpGXf26b0Rl1DZ4P_w2nBlqV4Uf7k0',
    appId: '1:879502825049:android:1f0d5565c811d97e71c348',
    messagingSenderId: '879502825049',
    projectId: 'doctor-appointment-a0e23',
    storageBucket: 'doctor-appointment-a0e23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMRFfcRa7M2PFRL_Wzk30MxR7pSlRwmSA',
    appId: '1:879502825049:ios:5503bfa86dae0dea71c348',
    messagingSenderId: '879502825049',
    projectId: 'doctor-appointment-a0e23',
    storageBucket: 'doctor-appointment-a0e23.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppoitment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtlQUnHlE0zYOVvFZWJeaV64naaPGlVhQ',
    appId: '1:879502825049:web:8245a43588f3b02f71c348',
    messagingSenderId: '879502825049',
    projectId: 'doctor-appointment-a0e23',
    authDomain: 'doctor-appointment-a0e23.firebaseapp.com',
    storageBucket: 'doctor-appointment-a0e23.firebasestorage.app',
    measurementId: 'G-TKZXGB96XK',
  );
}
